import { useState } from "react";
import type { DeploymentInfo } from "../../types/messages";

interface DeploymentCardProps {
  deployment: DeploymentInfo;
  serverName: string;
  downloadUrl: string | null;
  sessionId: string;
}

export function DeploymentCard({
  deployment,
  serverName,
  downloadUrl,
  sessionId,
}: DeploymentCardProps) {
  const [copied, setCopied] = useState<string | null>(null);

  // GitHub push state
  const [showGitHubForm, setShowGitHubForm] = useState(false);
  const [ghToken, setGhToken] = useState("");
  const [ghRepoName, setGhRepoName] = useState(`mcp-server-${serverName}`);
  const [ghPrivate, setGhPrivate] = useState(true);
  const [ghPushing, setGhPushing] = useState(false);
  const [ghResult, setGhResult] = useState<{
    url?: string;
    error?: string;
  } | null>(null);

  const copyToClipboard = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  };

  const handlePushToGitHub = async () => {
    if (!ghToken.trim() || !ghRepoName.trim()) return;
    setGhPushing(true);
    setGhResult(null);
    try {
      const resp = await fetch(`/api/push-github/${sessionId}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          token: ghToken.trim(),
          repo_name: ghRepoName.trim(),
          private: ghPrivate,
          description: `MCP server: ${serverName} — generated by MCP Factory`,
        }),
      });
      const data = await resp.json();
      if (resp.ok) {
        setGhResult({ url: data.repo_url });
        setShowGitHubForm(false);
      } else {
        setGhResult({ error: data.detail || "Push failed" });
      }
    } catch {
      setGhResult({ error: "Network error. Check your connection." });
    } finally {
      setGhPushing(false);
    }
  };

  const githubSection = (
    <>
      {!ghResult?.url && (
        <button
          className="download-button-secondary github-push-btn"
          onClick={() => setShowGitHubForm(!showGitHubForm)}
        >
          <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z" />
          </svg>
          Push to GitHub
        </button>
      )}

      {showGitHubForm && !ghResult?.url && (
        <div className="github-push-form">
          <div className="env-var-field">
            <label className="env-var-label">
              <code>GitHub PAT</code>
              <span className="env-var-hint">
                Needs <code>repo</code> scope.{" "}
                <a
                  href="https://github.com/settings/tokens/new"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Create one
                </a>
              </span>
            </label>
            <input
              type="password"
              className="env-var-input"
              placeholder="ghp_xxxxxxxxxxxxx"
              value={ghToken}
              onChange={(e) => setGhToken(e.target.value)}
            />
          </div>
          <div className="env-var-field">
            <label className="env-var-label">
              <code>Repository Name</code>
            </label>
            <input
              type="text"
              className="env-var-input"
              value={ghRepoName}
              onChange={(e) => setGhRepoName(e.target.value)}
            />
          </div>
          <div className="github-visibility-toggle">
            <label>
              <input
                type="checkbox"
                checked={ghPrivate}
                onChange={(e) => setGhPrivate(e.target.checked)}
              />
              Private repository
            </label>
          </div>
          <button
            className="github-push-submit"
            onClick={handlePushToGitHub}
            disabled={ghPushing || !ghToken.trim() || !ghRepoName.trim()}
          >
            {ghPushing ? "Pushing..." : "Create & Push"}
          </button>
          {ghResult?.error && (
            <p className="github-push-error">{ghResult.error}</p>
          )}
        </div>
      )}

      {ghResult?.url && (
        <div className="github-push-success">
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
            <polyline points="22 4 12 14.01 9 11.01" />
          </svg>
          <span>Pushed to </span>
          <a href={ghResult.url} target="_blank" rel="noopener noreferrer">
            {ghResult.url}
          </a>
        </div>
      )}
    </>
  );

  if (deployment.status === "failed") {
    return (
      <div className="deployment-card deployment-failed">
        <div className="deployment-card-header">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="12" cy="12" r="10" />
            <line x1="15" y1="9" x2="9" y2="15" />
            <line x1="9" y1="9" x2="15" y2="15" />
          </svg>
          <h3>Deployment Failed</h3>
        </div>
        <p className="deployment-error">{deployment.error}</p>
        <p className="deployment-fallback">
          You can still download the code and run it manually.
        </p>
        <div className="deployment-actions">
          {downloadUrl && (
            <a href={downloadUrl} className="download-button" download>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Download ZIP
            </a>
          )}
          {githubSection}
        </div>
      </div>
    );
  }

  return (
    <div className="deployment-card deployment-running">
      <div className="deployment-card-header">
        <div className="deployment-status-dot" />
        <h3>MCP Server is Live!</h3>
      </div>

      <div className="deployment-info">
        <div className="deployment-url-row">
          <span className="deployment-label">Server URL</span>
          <code className="deployment-url">{deployment.sse_url}</code>
          <button
            className="copy-btn"
            onClick={() => copyToClipboard(deployment.sse_url || "", "url")}
          >
            {copied === "url" ? "Copied!" : "Copy"}
          </button>
        </div>
      </div>

      <div className="deployment-configs">
        <h4>Connect to your MCP Client</h4>
        <p className="deployment-hint">
          Copy the config below and paste it into your MCP client settings.
        </p>

        <div className="config-tabs">
          <ConfigBlock
            label="Claude Desktop"
            hint={`Edit ~/Library/Application Support/Claude/claude_desktop_config.json (macOS) or %APPDATA%\\Claude\\claude_desktop_config.json (Windows). Requires Node.js (npx) installed. Restart Claude Desktop after saving.`}
            config={deployment.claude_desktop_config || deployment.client_config_json || ""}
            onCopy={(text) => copyToClipboard(text, "claude")}
            copied={copied === "claude"}
          />
          <ConfigBlock
            label="Cursor"
            hint="Edit .cursor/mcp.json in your project root or add via Cursor Settings > MCP"
            config={deployment.cursor_config || deployment.client_config_json || ""}
            onCopy={(text) => copyToClipboard(text, "cursor")}
            copied={copied === "cursor"}
          />
          <ConfigBlock
            label="Windsurf / Other"
            hint="Use the mcpServers JSON block in your client's MCP configuration"
            config={deployment.generic_config || deployment.client_config_json || ""}
            onCopy={(text) => copyToClipboard(text, "windsurf")}
            copied={copied === "windsurf"}
          />
        </div>
      </div>

      <div className="deployment-actions">
        {downloadUrl && (
          <a href={downloadUrl} className="download-button-secondary" download>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
              <polyline points="7 10 12 15 17 10" />
              <line x1="12" y1="15" x2="12" y2="3" />
            </svg>
            Download Source Code
          </a>
        )}
        {githubSection}
      </div>
    </div>
  );
}

function ConfigBlock({
  label,
  hint,
  config,
  onCopy,
  copied,
}: {
  label: string;
  hint: string;
  config: string;
  onCopy: (text: string) => void;
  copied: boolean;
}) {
  const [expanded, setExpanded] = useState(label === "Claude Desktop");

  return (
    <div className="config-block">
      <button
        className="config-block-header"
        onClick={() => setExpanded(!expanded)}
      >
        <span className="config-block-label">{label}</span>
        <svg
          width="14"
          height="14"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          style={{
            transform: expanded ? "rotate(180deg)" : "rotate(0deg)",
            transition: "transform 0.2s",
          }}
        >
          <polyline points="6 9 12 15 18 9" />
        </svg>
      </button>
      {expanded && (
        <div className="config-block-body">
          <p className="config-hint">{hint}</p>
          <div className="config-code-wrapper">
            <pre className="config-code">{config}</pre>
            <button
              className="copy-btn config-copy"
              onClick={() => onCopy(config)}
            >
              {copied ? "Copied!" : "Copy"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
